version: '3.8'

services:
  seanamoroso:
    container_name: seanamoroso
    build:
      context: .
      target: prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod
    networks:
      - seanamo_network
    restart: unless-stopped

  cloudflare-seanamoroso:
    image: cloudflare/cloudflared
    container_name: cloudflare-seanamoroso
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - seanamo_network
    depends_on:
      - seanamoroso

networks:
  seanamo_network:
    driver: bridge