version: '3.8'

services:
  seanamoroso:
    build:
      context: .
      target: prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod
    restart: unless-stopped

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - seanamoroso