name: Deploy to Production

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up environment
        run: |
          echo "NODE_ENV=production" >> .env.prod
          
      - name: Stop existing containers
        run: |
          docker compose -f docker-compose.prod.yaml down || true
          
      - name: 🔧 Pull or Build Images
        run: |
          docker compose -f docker-compose.prod.yaml pull || true
          docker compose -f docker-compose.prod.yaml build

      - name: 🚀 Start Services
        run: |
          docker compose -f docker-compose.prod.yaml up -d

      - name: ✅ Show Running Containers
        run: docker ps
